export let codesPrestationsBruto = {
	"SUW": "Heures volontaires supplémentaires",
	"101":"PRIME JOUR FERIE (100% - max 7,6h)",
	"1T4":"% PP EQUIP",
	"283":"PRIME VETEMENTS",
	"283":"REMUN.VETE",
	"2C5":"RETENUE REPAS",
	"390":"FRAIS DE DEPLACEMENT PRIVE",
	"403":"COMMISSION",
	"440":"FRAIS DEPLACEMENT TRANSPORT EN COMMUN",
	"452":"DEDUC. GARANTIE VETMENT",
	"454":"RETENUE REPAS",
	"456":"DOUBLE PAIEMENT RETENUE NET INTERIMAIRE",
	"459":"ACOMPTE MANUEL",
	"4B6":"PARKING",
	"502":"PRIME DE NUIT (1,2460€ max 5h 24:00 - 05:00, génére un 1T5)",
	"504":"PRIME DIMANCHE (2€/u - max 6u - Max 12€)",
	"517":"PRIME PENSION (h. prestees x salaire x 0,76)",
	"775":"CHEQUE REPAS",
	"861":"PRIME ANNUELLE",
	"A25":"JOUR FERIE (par defaut 7,6h, liee a 1F4)",
	"A25":"JOUR FERIE, NON PRESTE, NON FACTURE (liee a 1F4)",
	"AA ":"ABSENCE JUSTIFIEE",
	"ATA":"ACCIDENT TRAVAIL (non facturé, non rémunéré)",
	"AV ":"ABSENCE INJUSTIFIEE",
	"E45":"REMBOURSEMENT GARANTIE VETEMENT",
	"FM ":"FORCE MAJEURE",
	"M1 ":"MALADIE (avec justificatif - max 7.6h)",
	"MN ":"MALADIE (sans justificatif)",
	"P  ":"HEURES PRESTEES",
	"PAT":"CONGES PATERNITE",
	"PC ":"PETIT CHOMAGE (congé parental 3j)",
	"RF ":"RAISONS IMPERIEUSES (maladie enfants)",
	"SUW":"HEURES SUPPLEMENTAIRES VOLONTAIRE",
	"VSN":"HEURES VACANCES SENIORS",
	"YQ96":"ECO CHEQUES (encodage manuel sur fiche de salaire intérimaire)",

}

export let codesPrestationsInterpreted = {
	"101 ":"PRIME JOUR FERIE (100% - max 7,6h)",
	"1T4 ":"% PP EQUIP",
	"283 ":"PRIME VETEMENTS",
	"283 ":"REMUN.VETE",
	"2C5 ":"RETENUE REPAS",
	"390 ":"FRAIS DE DEPLACEMENT PRIVE",
	"403 ":"COMMISSION",
	"440 ":"FRAIS DEPLACEMENT TRANSPORT EN COMMUN",
	"452 ":"DEDUC. GARANTIE VETMENT",
	"454 ":"RETENUE REPAS",
	"456 ":"DOUBLE PAIEMENT RETENUE NET INTERIMAIRE",
	"459 ":"ACOMPTE MANUEL",
	"4B6 ":"PARKING",
	"502 ":"PRIME DE NUIT (1,2460€ max 5h 24:00 - 05:00, génére un 1T5)",
	"504 ":"PRIME DIMANCHE (2€/u - max 6u - Max 12€)",
	"517 ":"PRIME PENSION (h. prestees x salaire x 0,76)",
	"775 ":"CHEQUE REPAS",
	"861 ":"PRIME ANNUELLE",
	"A25 ":"JOUR FERIE (par defaut 7,6h, liee a 1F4)",
	"A25 ":"JOUR FERIE, NON PRESTE, NON FACTURE (liee a 1F4)",
	"AA  ":"ABSENCE JUSTIFIEE",
	"ATA ":"ACCIDENT TRAVAIL (non facturé, non rémunéré)",
	"AV  ":"ABSENCE INJUSTIFIEE",
	"E45 ":"REMBOURSEMENT GARANTIE VETEMENT",
	"FM  ":"FORCE MAJEURE",
	"M1  ":"MALADIE (avec justificatif - max 7.6h)",
	"MN  ":"MALADIE (sans justificatif)",
	"P   ":"HEURES PRESTEES",
	"P   ":"HEURES NON FACTUREES",
	"PAT ":"CONGES PATERNITE",
	"PC  ":"PETIT CHOMAGE (congé parental 3j)",
	"RF  ":"RAISONS IMPERIEUSES (maladie enfants)",
	"SUW ":"HEURES SUPPLEMENTAIRES VOLONTAIRE",
	"VSN ":"HEURES VACANCES SENIORS",
	"YQ96":"ECO CHEQUES (encodage manuel sur fiche de salaire intérimaire)",

}


